#!/usr/bin/env python3
"""
Module to interact with MongoDB collections using PyMongo.

This module provides a function to insert a new document into a
specified MongoDB collection.
"""


def insert_school(mongo_collection, **kwargs):
    '''
    Inserts a new document into a MongoDB collection.

    Parameters:
    -----------
    mongo_collection : pymongo.collection.Collection
        The collection object where the document will be inserted. This
        should be a valid PyMongo Collection object connected to a MongoDB
        database.
    Returns:
    --------
    Any
        The unique identifier (ID) of the newly inserted document. This ID is
        usually an instance of `ObjectId`.
    Notes:
    ------
    The inserted document will automatically have an `_id` field generated by
    MongoDB if not provided. This function uses `insert_one()` under the hood,
    which is the recommended way to insert a single document.
    '''

    # Insert the document into the collection and return the document's ID.
    document_id = mongo_collection.insert_one(kwargs).inserted_id

    return document_id
